//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eisight.Meter
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0-preview-30131-0887")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.esightenergy.com/esight/WS/", ConfigurationName="Eisight.Meter.MeterSoap")]
    public interface MeterSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.esightenergy.com/esight/WS/GetMeters", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Eisight.Meter.ArrayOfXElement> GetMetersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.esightenergy.com/esight/WS/GetMetersAsObjects", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Eisight.Meter.MeterPath[]> GetMetersAsObjectsAsync(string u, string pw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.esightenergy.com/esight/WS/GetMetersAsObjectsSecurityContext", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Eisight.Meter.MeterPath[]> GetMetersAsObjectsSecurityContextAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.esightenergy.com/esight/WS/GetMetersAsObjectsSecurityContextHash", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GetMetersAsObjectsSecurityContextHashAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.esightenergy.com/esight/WS/GetMetersForCompanyID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Eisight.Meter.ArrayOfXElement> GetMetersForCompanyIDAsync(int companyID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.esightenergy.com/esight/WS/GetMetersForSiteID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Eisight.Meter.ArrayOfXElement> GetMetersForSiteIDAsync(int siteID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.esightenergy.com/esight/WS/GetMetersForFilterID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Eisight.Meter.ArrayOfXElement> GetMetersForFilterIDAsync(int filterID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.esightenergy.com/esight/WS/GetMeterIDFromNameAndSiteID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> GetMeterIDFromNameAndSiteIDAsync(string meterName, int siteID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.esightenergy.com/esight/WS/GetMeterIDFromCodeAndSiteID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> GetMeterIDFromCodeAndSiteIDAsync(string meterCode, int siteID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.esightenergy.com/esight/WS/GetMeter", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Eisight.Meter.MeterInfo> GetMeterAsync(int meterID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.esightenergy.com/esight/WS/SetMeter", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Eisight.Meter.ResultInfo> SetMeterAsync(Eisight.Meter.MeterInfo meterInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.esightenergy.com/esight/WS/SetMeterWithSecurity", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Eisight.Meter.SetMeterWithSecurityResponse> SetMeterWithSecurityAsync(Eisight.Meter.SetMeterWithSecurityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.esightenergy.com/esight/WS/DeleteMeter", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Eisight.Meter.ResultInfo> DeleteMeterAsync(int meterID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.esightenergy.com/esight/WS/GetMeterUnitValue", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GetMeterUnitValueAsync(int meterID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.esightenergy.com/esight/WS/GetSiteCodeForMeter", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GetSiteCodeForMeterAsync(int meterID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.esightenergy.com/esight/WS/GetSiteMeterCodeForMeter", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GetSiteMeterCodeForMeterAsync(int meterID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.esightenergy.com/esight/WS/GetMeterTypes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Eisight.Meter.ArrayOfXElement> GetMeterTypesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.esightenergy.com/esight/WS/GetMeterModels", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Eisight.Meter.ArrayOfXElement> GetMeterModelsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.esightenergy.com/esight/WS/GetMeterModel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Eisight.Meter.MeterModel> GetMeterModelAsync(int meterModelId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.esightenergy.com/esight/WS/GetReadFrequencies", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Eisight.Meter.ArrayOfXElement> GetReadFrequenciesAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0-preview-30131-0887")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esightenergy.com/esight/WS/")]
    public partial class MeterModel
    {
        
        private int meterModelIdField;
        
        private int manufacturerIdField;
        
        private string manufacturerDescriptionField;
        
        private string modelNumberField;
        
        private string readingFormatField;
        
        private string notesField;
        
        private int numberOfDigitsToLeftOfDecimalPointField;
        
        private int numberOfDigitsToRightOfDecimalPointField;
        
        private int numMetersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int MeterModelId
        {
            get
            {
                return this.meterModelIdField;
            }
            set
            {
                this.meterModelIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ManufacturerId
        {
            get
            {
                return this.manufacturerIdField;
            }
            set
            {
                this.manufacturerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ManufacturerDescription
        {
            get
            {
                return this.manufacturerDescriptionField;
            }
            set
            {
                this.manufacturerDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ModelNumber
        {
            get
            {
                return this.modelNumberField;
            }
            set
            {
                this.modelNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ReadingFormat
        {
            get
            {
                return this.readingFormatField;
            }
            set
            {
                this.readingFormatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Notes
        {
            get
            {
                return this.notesField;
            }
            set
            {
                this.notesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int NumberOfDigitsToLeftOfDecimalPoint
        {
            get
            {
                return this.numberOfDigitsToLeftOfDecimalPointField;
            }
            set
            {
                this.numberOfDigitsToLeftOfDecimalPointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int NumberOfDigitsToRightOfDecimalPoint
        {
            get
            {
                return this.numberOfDigitsToRightOfDecimalPointField;
            }
            set
            {
                this.numberOfDigitsToRightOfDecimalPointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int NumMeters
        {
            get
            {
                return this.numMetersField;
            }
            set
            {
                this.numMetersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0-preview-30131-0887")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esightenergy.com/esight/WS/")]
    public partial class SecurityContext
    {
        
        private string userIdField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string userId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0-preview-30131-0887")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esightenergy.com/esight/WS/")]
    public partial class ResultInfo
    {
        
        private bool successField;
        
        private int updateIDField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Success
        {
            get
            {
                return this.successField;
            }
            set
            {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int UpdateID
        {
            get
            {
                return this.updateIDField;
            }
            set
            {
                this.updateIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ErrorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0-preview-30131-0887")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esightenergy.com/esight/WS/")]
    public partial class clsMeterTypeHistory
    {
        
        private int meterIDField;
        
        private int meterTypeIDField;
        
        private double correctionFactorField;
        
        private System.DateTime validToDateField;
        
        private int idField;
        
        private DatabaseActionEnum actionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int MeterID
        {
            get
            {
                return this.meterIDField;
            }
            set
            {
                this.meterIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int MeterTypeID
        {
            get
            {
                return this.meterTypeIDField;
            }
            set
            {
                this.meterTypeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double CorrectionFactor
        {
            get
            {
                return this.correctionFactorField;
            }
            set
            {
                this.correctionFactorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime ValidToDate
        {
            get
            {
                return this.validToDateField;
            }
            set
            {
                this.validToDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public DatabaseActionEnum Action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0-preview-30131-0887")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esightenergy.com/esight/WS/")]
    public enum DatabaseActionEnum
    {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Insert,
        
        /// <remarks/>
        Edit,
        
        /// <remarks/>
        Delete,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0-preview-30131-0887")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esightenergy.com/esight/WS/")]
    public partial class clsAvailableCapacityHistory
    {
        
        private int availableCapacityHistoryIDField;
        
        private System.DateTime effectiveDateField;
        
        private int meterIDField;
        
        private double valueField;
        
        private DatabaseActionEnum actionField;
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int AvailableCapacityHistoryID
        {
            get
            {
                return this.availableCapacityHistoryIDField;
            }
            set
            {
                this.availableCapacityHistoryIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime EffectiveDate
        {
            get
            {
                return this.effectiveDateField;
            }
            set
            {
                this.effectiveDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int MeterID
        {
            get
            {
                return this.meterIDField;
            }
            set
            {
                this.meterIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public DatabaseActionEnum Action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0-preview-30131-0887")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esightenergy.com/esight/WS/")]
    public partial class clsActivePeriodInfo
    {
        
        private int activePeriodIDField;
        
        private int siteIDField;
        
        private int meterIDField;
        
        private int fromMonthField;
        
        private int toMonthField;
        
        private int fromDayField;
        
        private int toDayField;
        
        private int fromTimeField;
        
        private int toTimeField;
        
        private int percentageActiveField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ActivePeriodID
        {
            get
            {
                return this.activePeriodIDField;
            }
            set
            {
                this.activePeriodIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int SiteID
        {
            get
            {
                return this.siteIDField;
            }
            set
            {
                this.siteIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int MeterID
        {
            get
            {
                return this.meterIDField;
            }
            set
            {
                this.meterIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int FromMonth
        {
            get
            {
                return this.fromMonthField;
            }
            set
            {
                this.fromMonthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int ToMonth
        {
            get
            {
                return this.toMonthField;
            }
            set
            {
                this.toMonthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int FromDay
        {
            get
            {
                return this.fromDayField;
            }
            set
            {
                this.fromDayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int ToDay
        {
            get
            {
                return this.toDayField;
            }
            set
            {
                this.toDayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int FromTime
        {
            get
            {
                return this.fromTimeField;
            }
            set
            {
                this.fromTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int ToTime
        {
            get
            {
                return this.toTimeField;
            }
            set
            {
                this.toTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int PercentageActive
        {
            get
            {
                return this.percentageActiveField;
            }
            set
            {
                this.percentageActiveField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0-preview-30131-0887")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esightenergy.com/esight/WS/")]
    public partial class MeterInfo
    {
        
        private int meterIDField;
        
        private int parentIDField;
        
        private int parentTypeIDField;
        
        private string nameField;
        
        private int metertypeField;
        
        private string meterCodeField;
        
        private bool enabledField;
        
        private int taxRateIDField;
        
        private int consultantIDField;
        
        private bool includeTaxInCostField;
        
        private int treeViewIconField;
        
        private int typeIDField;
        
        private int meterReadFrequencyIDField;
        
        private int costTariffIDField;
        
        private string costTariffTextField;
        
        private int revenueTariffIDField;
        
        private string revenueTariffTextField;
        
        private bool cumulativeReadingsField;
        
        private int suspectReadingsStdDevField;
        
        private int meterModelIDField;
        
        private string serialNumberField;
        
        private string meterNumberPrefixField;
        
        private string meterNumberField;
        
        private string dataImportCodeField;
        
        private string dataImportTagField;
        
        private int supplierIDField;
        
        private bool tenantBillingMeterField;
        
        private bool invoiceBillingMeterField;
        
        private System.Nullable<System.DateTime> installationDateField;
        
        private System.Nullable<double> initialReadingField;
        
        private double targetPerReadingField;
        
        private bool autoAdjustTargetField;
        
        private double tolerancePercentageField;
        
        private double additionalHeatEnergyField;
        
        private double correctionFactorField;
        
        private string imageFileNameField;
        
        private int userDefinedLookupID1Field;
        
        private int userDefinedLookupID2Field;
        
        private string userDefinedTxtBox1Field;
        
        private string userDefinedTxtBox2Field;
        
        private double meterSqField;
        
        private double meterCuField;
        
        private int numberOfRegistersField;
        
        private int validationTypeIDField;
        
        private int meterServiceIDField;
        
        private int meterBuildingIDField;
        
        private int readingTypeIDField;
        
        private int benchmarkDataTypeIDField;
        
        private bool proRataDataField;
        
        private System.Nullable<System.DateTime> mOPStartDateField;
        
        private System.Nullable<System.DateTime> mOPEndDateField;
        
        private double mOPAnnualCostField;
        
        private int meterOperatorIDField;
        
        private int mOPCurrencyIDField;
        
        private bool emissionsReportingField;
        
        private int batteryLifeField;
        
        private int associatedProductionMeterIDField;
        
        private int dDTypeIDField;
        
        private int calculateIntervalIDField;
        
        private bool efficiencyMeterField;
        
        private int mainMeterIDField;
        
        private string linkURLField;
        
        private bool metricField;
        
        private bool mainMeterField;
        
        private bool internalBillingField;
        
        private clsActivePeriodInfo[] activePeriodsListField;
        
        private bool eTCurveField;
        
        private int fuelTypeIDField;
        
        private int voltageIDField;
        
        private double transcoAQField;
        
        private bool aMRField;
        
        private string contractNumberField;
        
        private string internalRefField;
        
        private System.Nullable<int> meterPublicHolidayPercentActiveField;
        
        private System.Nullable<int> kVarhMeterIDField;
        
        private bool cRCSourceField;
        
        private System.Nullable<double> cCLReliefField;
        
        private string contractTypeField;
        
        private int customerSavingsPercentageField;
        
        private double dHWSSetPointLevelField;
        
        private double heatingSetPointLevelField;
        
        private System.Nullable<int> meterReadFrequencyUnitIDField;
        
        private System.Nullable<int> meterReadFrequencyValueField;
        
        private bool hasMeterDataField;
        
        private System.Nullable<int> gHGScopeIDField;
        
        private clsAvailableCapacityHistory[] availableCapacityHistoryField;
        
        private clsMeterTypeHistory[] meterTypeHistoryField;
        
        private bool saveDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int MeterID
        {
            get
            {
                return this.meterIDField;
            }
            set
            {
                this.meterIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ParentID
        {
            get
            {
                return this.parentIDField;
            }
            set
            {
                this.parentIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int ParentTypeID
        {
            get
            {
                return this.parentTypeIDField;
            }
            set
            {
                this.parentTypeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Metertype
        {
            get
            {
                return this.metertypeField;
            }
            set
            {
                this.metertypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string MeterCode
        {
            get
            {
                return this.meterCodeField;
            }
            set
            {
                this.meterCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool Enabled
        {
            get
            {
                return this.enabledField;
            }
            set
            {
                this.enabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int TaxRateID
        {
            get
            {
                return this.taxRateIDField;
            }
            set
            {
                this.taxRateIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int ConsultantID
        {
            get
            {
                return this.consultantIDField;
            }
            set
            {
                this.consultantIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool IncludeTaxInCost
        {
            get
            {
                return this.includeTaxInCostField;
            }
            set
            {
                this.includeTaxInCostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int TreeViewIcon
        {
            get
            {
                return this.treeViewIconField;
            }
            set
            {
                this.treeViewIconField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int TypeID
        {
            get
            {
                return this.typeIDField;
            }
            set
            {
                this.typeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int MeterReadFrequencyID
        {
            get
            {
                return this.meterReadFrequencyIDField;
            }
            set
            {
                this.meterReadFrequencyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int CostTariffID
        {
            get
            {
                return this.costTariffIDField;
            }
            set
            {
                this.costTariffIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string CostTariffText
        {
            get
            {
                return this.costTariffTextField;
            }
            set
            {
                this.costTariffTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public int RevenueTariffID
        {
            get
            {
                return this.revenueTariffIDField;
            }
            set
            {
                this.revenueTariffIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string RevenueTariffText
        {
            get
            {
                return this.revenueTariffTextField;
            }
            set
            {
                this.revenueTariffTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public bool CumulativeReadings
        {
            get
            {
                return this.cumulativeReadingsField;
            }
            set
            {
                this.cumulativeReadingsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public int SuspectReadingsStdDev
        {
            get
            {
                return this.suspectReadingsStdDevField;
            }
            set
            {
                this.suspectReadingsStdDevField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public int MeterModelID
        {
            get
            {
                return this.meterModelIDField;
            }
            set
            {
                this.meterModelIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string SerialNumber
        {
            get
            {
                return this.serialNumberField;
            }
            set
            {
                this.serialNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string MeterNumberPrefix
        {
            get
            {
                return this.meterNumberPrefixField;
            }
            set
            {
                this.meterNumberPrefixField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string MeterNumber
        {
            get
            {
                return this.meterNumberField;
            }
            set
            {
                this.meterNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string DataImportCode
        {
            get
            {
                return this.dataImportCodeField;
            }
            set
            {
                this.dataImportCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string DataImportTag
        {
            get
            {
                return this.dataImportTagField;
            }
            set
            {
                this.dataImportTagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public int SupplierID
        {
            get
            {
                return this.supplierIDField;
            }
            set
            {
                this.supplierIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public bool TenantBillingMeter
        {
            get
            {
                return this.tenantBillingMeterField;
            }
            set
            {
                this.tenantBillingMeterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public bool InvoiceBillingMeter
        {
            get
            {
                return this.invoiceBillingMeterField;
            }
            set
            {
                this.invoiceBillingMeterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=28)]
        public System.Nullable<System.DateTime> InstallationDate
        {
            get
            {
                return this.installationDateField;
            }
            set
            {
                this.installationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=29)]
        public System.Nullable<double> InitialReading
        {
            get
            {
                return this.initialReadingField;
            }
            set
            {
                this.initialReadingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public double TargetPerReading
        {
            get
            {
                return this.targetPerReadingField;
            }
            set
            {
                this.targetPerReadingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public bool AutoAdjustTarget
        {
            get
            {
                return this.autoAdjustTargetField;
            }
            set
            {
                this.autoAdjustTargetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public double TolerancePercentage
        {
            get
            {
                return this.tolerancePercentageField;
            }
            set
            {
                this.tolerancePercentageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public double AdditionalHeatEnergy
        {
            get
            {
                return this.additionalHeatEnergyField;
            }
            set
            {
                this.additionalHeatEnergyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public double CorrectionFactor
        {
            get
            {
                return this.correctionFactorField;
            }
            set
            {
                this.correctionFactorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public string ImageFileName
        {
            get
            {
                return this.imageFileNameField;
            }
            set
            {
                this.imageFileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public int UserDefinedLookupID1
        {
            get
            {
                return this.userDefinedLookupID1Field;
            }
            set
            {
                this.userDefinedLookupID1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public int UserDefinedLookupID2
        {
            get
            {
                return this.userDefinedLookupID2Field;
            }
            set
            {
                this.userDefinedLookupID2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public string UserDefinedTxtBox1
        {
            get
            {
                return this.userDefinedTxtBox1Field;
            }
            set
            {
                this.userDefinedTxtBox1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public string UserDefinedTxtBox2
        {
            get
            {
                return this.userDefinedTxtBox2Field;
            }
            set
            {
                this.userDefinedTxtBox2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public double MeterSq
        {
            get
            {
                return this.meterSqField;
            }
            set
            {
                this.meterSqField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public double MeterCu
        {
            get
            {
                return this.meterCuField;
            }
            set
            {
                this.meterCuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=42)]
        public int NumberOfRegisters
        {
            get
            {
                return this.numberOfRegistersField;
            }
            set
            {
                this.numberOfRegistersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=43)]
        public int ValidationTypeID
        {
            get
            {
                return this.validationTypeIDField;
            }
            set
            {
                this.validationTypeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=44)]
        public int MeterServiceID
        {
            get
            {
                return this.meterServiceIDField;
            }
            set
            {
                this.meterServiceIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=45)]
        public int MeterBuildingID
        {
            get
            {
                return this.meterBuildingIDField;
            }
            set
            {
                this.meterBuildingIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=46)]
        public int ReadingTypeID
        {
            get
            {
                return this.readingTypeIDField;
            }
            set
            {
                this.readingTypeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=47)]
        public int BenchmarkDataTypeID
        {
            get
            {
                return this.benchmarkDataTypeIDField;
            }
            set
            {
                this.benchmarkDataTypeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=48)]
        public bool ProRataData
        {
            get
            {
                return this.proRataDataField;
            }
            set
            {
                this.proRataDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=49)]
        public System.Nullable<System.DateTime> MOPStartDate
        {
            get
            {
                return this.mOPStartDateField;
            }
            set
            {
                this.mOPStartDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=50)]
        public System.Nullable<System.DateTime> MOPEndDate
        {
            get
            {
                return this.mOPEndDateField;
            }
            set
            {
                this.mOPEndDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=51)]
        public double MOPAnnualCost
        {
            get
            {
                return this.mOPAnnualCostField;
            }
            set
            {
                this.mOPAnnualCostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=52)]
        public int MeterOperatorID
        {
            get
            {
                return this.meterOperatorIDField;
            }
            set
            {
                this.meterOperatorIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=53)]
        public int MOPCurrencyID
        {
            get
            {
                return this.mOPCurrencyIDField;
            }
            set
            {
                this.mOPCurrencyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=54)]
        public bool EmissionsReporting
        {
            get
            {
                return this.emissionsReportingField;
            }
            set
            {
                this.emissionsReportingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=55)]
        public int BatteryLife
        {
            get
            {
                return this.batteryLifeField;
            }
            set
            {
                this.batteryLifeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=56)]
        public int AssociatedProductionMeterID
        {
            get
            {
                return this.associatedProductionMeterIDField;
            }
            set
            {
                this.associatedProductionMeterIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=57)]
        public int DDTypeID
        {
            get
            {
                return this.dDTypeIDField;
            }
            set
            {
                this.dDTypeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=58)]
        public int CalculateIntervalID
        {
            get
            {
                return this.calculateIntervalIDField;
            }
            set
            {
                this.calculateIntervalIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=59)]
        public bool EfficiencyMeter
        {
            get
            {
                return this.efficiencyMeterField;
            }
            set
            {
                this.efficiencyMeterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=60)]
        public int MainMeterID
        {
            get
            {
                return this.mainMeterIDField;
            }
            set
            {
                this.mainMeterIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=61)]
        public string LinkURL
        {
            get
            {
                return this.linkURLField;
            }
            set
            {
                this.linkURLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=62)]
        public bool Metric
        {
            get
            {
                return this.metricField;
            }
            set
            {
                this.metricField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=63)]
        public bool MainMeter
        {
            get
            {
                return this.mainMeterField;
            }
            set
            {
                this.mainMeterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=64)]
        public bool InternalBilling
        {
            get
            {
                return this.internalBillingField;
            }
            set
            {
                this.internalBillingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=65)]
        public clsActivePeriodInfo[] ActivePeriodsList
        {
            get
            {
                return this.activePeriodsListField;
            }
            set
            {
                this.activePeriodsListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=66)]
        public bool ETCurve
        {
            get
            {
                return this.eTCurveField;
            }
            set
            {
                this.eTCurveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=67)]
        public int FuelTypeID
        {
            get
            {
                return this.fuelTypeIDField;
            }
            set
            {
                this.fuelTypeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=68)]
        public int VoltageID
        {
            get
            {
                return this.voltageIDField;
            }
            set
            {
                this.voltageIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=69)]
        public double TranscoAQ
        {
            get
            {
                return this.transcoAQField;
            }
            set
            {
                this.transcoAQField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=70)]
        public bool AMR
        {
            get
            {
                return this.aMRField;
            }
            set
            {
                this.aMRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=71)]
        public string ContractNumber
        {
            get
            {
                return this.contractNumberField;
            }
            set
            {
                this.contractNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=72)]
        public string InternalRef
        {
            get
            {
                return this.internalRefField;
            }
            set
            {
                this.internalRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=73)]
        public System.Nullable<int> MeterPublicHolidayPercentActive
        {
            get
            {
                return this.meterPublicHolidayPercentActiveField;
            }
            set
            {
                this.meterPublicHolidayPercentActiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=74)]
        public System.Nullable<int> KVarhMeterID
        {
            get
            {
                return this.kVarhMeterIDField;
            }
            set
            {
                this.kVarhMeterIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=75)]
        public bool CRCSource
        {
            get
            {
                return this.cRCSourceField;
            }
            set
            {
                this.cRCSourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=76)]
        public System.Nullable<double> CCLRelief
        {
            get
            {
                return this.cCLReliefField;
            }
            set
            {
                this.cCLReliefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=77)]
        public string ContractType
        {
            get
            {
                return this.contractTypeField;
            }
            set
            {
                this.contractTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=78)]
        public int CustomerSavingsPercentage
        {
            get
            {
                return this.customerSavingsPercentageField;
            }
            set
            {
                this.customerSavingsPercentageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=79)]
        public double DHWSSetPointLevel
        {
            get
            {
                return this.dHWSSetPointLevelField;
            }
            set
            {
                this.dHWSSetPointLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=80)]
        public double HeatingSetPointLevel
        {
            get
            {
                return this.heatingSetPointLevelField;
            }
            set
            {
                this.heatingSetPointLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=81)]
        public System.Nullable<int> MeterReadFrequencyUnitID
        {
            get
            {
                return this.meterReadFrequencyUnitIDField;
            }
            set
            {
                this.meterReadFrequencyUnitIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=82)]
        public System.Nullable<int> MeterReadFrequencyValue
        {
            get
            {
                return this.meterReadFrequencyValueField;
            }
            set
            {
                this.meterReadFrequencyValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=83)]
        public bool HasMeterData
        {
            get
            {
                return this.hasMeterDataField;
            }
            set
            {
                this.hasMeterDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=84)]
        public System.Nullable<int> GHGScopeID
        {
            get
            {
                return this.gHGScopeIDField;
            }
            set
            {
                this.gHGScopeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=85)]
        public clsAvailableCapacityHistory[] AvailableCapacityHistory
        {
            get
            {
                return this.availableCapacityHistoryField;
            }
            set
            {
                this.availableCapacityHistoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=86)]
        public clsMeterTypeHistory[] MeterTypeHistory
        {
            get
            {
                return this.meterTypeHistoryField;
            }
            set
            {
                this.meterTypeHistoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=87)]
        public bool SaveData
        {
            get
            {
                return this.saveDataField;
            }
            set
            {
                this.saveDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0-preview-30131-0887")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esightenergy.com/esight/WS/")]
    public partial class MeterPath
    {
        
        private int meterIDField;
        
        private string siteMeterCodeField;
        
        private string pathField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int MeterID
        {
            get
            {
                return this.meterIDField;
            }
            set
            {
                this.meterIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SiteMeterCode
        {
            get
            {
                return this.siteMeterCodeField;
            }
            set
            {
                this.siteMeterCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Path
        {
            get
            {
                return this.pathField;
            }
            set
            {
                this.pathField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0-preview-30131-0887")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetMeterWithSecurity", WrapperNamespace="http://www.esightenergy.com/esight/WS/", IsWrapped=true)]
    public partial class SetMeterWithSecurityRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.esightenergy.com/esight/WS/")]
        public Eisight.Meter.SecurityContext SecurityContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.esightenergy.com/esight/WS/", Order=0)]
        public Eisight.Meter.MeterInfo meterInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.esightenergy.com/esight/WS/", Order=1)]
        public bool encrypted;
        
        public SetMeterWithSecurityRequest()
        {
        }
        
        public SetMeterWithSecurityRequest(Eisight.Meter.SecurityContext SecurityContext, Eisight.Meter.MeterInfo meterInfo, bool encrypted)
        {
            this.SecurityContext = SecurityContext;
            this.meterInfo = meterInfo;
            this.encrypted = encrypted;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0-preview-30131-0887")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetMeterWithSecurityResponse", WrapperNamespace="http://www.esightenergy.com/esight/WS/", IsWrapped=true)]
    public partial class SetMeterWithSecurityResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.esightenergy.com/esight/WS/")]
        public Eisight.Meter.SecurityContext SecurityContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.esightenergy.com/esight/WS/", Order=0)]
        public Eisight.Meter.ResultInfo SetMeterWithSecurityResult;
        
        public SetMeterWithSecurityResponse()
        {
        }
        
        public SetMeterWithSecurityResponse(Eisight.Meter.SecurityContext SecurityContext, Eisight.Meter.ResultInfo SetMeterWithSecurityResult)
        {
            this.SecurityContext = SecurityContext;
            this.SetMeterWithSecurityResult = SetMeterWithSecurityResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0-preview-30131-0887")]
    public interface MeterSoapChannel : Eisight.Meter.MeterSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0-preview-30131-0887")]
    public partial class MeterSoapClient : System.ServiceModel.ClientBase<Eisight.Meter.MeterSoap>, Eisight.Meter.MeterSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MeterSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(MeterSoapClient.GetBindingForEndpoint(endpointConfiguration), MeterSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MeterSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MeterSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MeterSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MeterSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MeterSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<Eisight.Meter.ArrayOfXElement> GetMetersAsync()
        {
            return base.Channel.GetMetersAsync();
        }
        
        public System.Threading.Tasks.Task<Eisight.Meter.MeterPath[]> GetMetersAsObjectsAsync(string u, string pw)
        {
            return base.Channel.GetMetersAsObjectsAsync(u, pw);
        }
        
        public System.Threading.Tasks.Task<Eisight.Meter.MeterPath[]> GetMetersAsObjectsSecurityContextAsync()
        {
            return base.Channel.GetMetersAsObjectsSecurityContextAsync();
        }
        
        public System.Threading.Tasks.Task<string> GetMetersAsObjectsSecurityContextHashAsync()
        {
            return base.Channel.GetMetersAsObjectsSecurityContextHashAsync();
        }
        
        public System.Threading.Tasks.Task<Eisight.Meter.ArrayOfXElement> GetMetersForCompanyIDAsync(int companyID)
        {
            return base.Channel.GetMetersForCompanyIDAsync(companyID);
        }
        
        public System.Threading.Tasks.Task<Eisight.Meter.ArrayOfXElement> GetMetersForSiteIDAsync(int siteID)
        {
            return base.Channel.GetMetersForSiteIDAsync(siteID);
        }
        
        public System.Threading.Tasks.Task<Eisight.Meter.ArrayOfXElement> GetMetersForFilterIDAsync(int filterID)
        {
            return base.Channel.GetMetersForFilterIDAsync(filterID);
        }
        
        public System.Threading.Tasks.Task<int> GetMeterIDFromNameAndSiteIDAsync(string meterName, int siteID)
        {
            return base.Channel.GetMeterIDFromNameAndSiteIDAsync(meterName, siteID);
        }
        
        public System.Threading.Tasks.Task<int> GetMeterIDFromCodeAndSiteIDAsync(string meterCode, int siteID)
        {
            return base.Channel.GetMeterIDFromCodeAndSiteIDAsync(meterCode, siteID);
        }
        
        public System.Threading.Tasks.Task<Eisight.Meter.MeterInfo> GetMeterAsync(int meterID)
        {
            return base.Channel.GetMeterAsync(meterID);
        }
        
        public System.Threading.Tasks.Task<Eisight.Meter.ResultInfo> SetMeterAsync(Eisight.Meter.MeterInfo meterInfo)
        {
            return base.Channel.SetMeterAsync(meterInfo);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Eisight.Meter.SetMeterWithSecurityResponse> Eisight.Meter.MeterSoap.SetMeterWithSecurityAsync(Eisight.Meter.SetMeterWithSecurityRequest request)
        {
            return base.Channel.SetMeterWithSecurityAsync(request);
        }
        
        public System.Threading.Tasks.Task<Eisight.Meter.SetMeterWithSecurityResponse> SetMeterWithSecurityAsync(Eisight.Meter.SecurityContext SecurityContext, Eisight.Meter.MeterInfo meterInfo, bool encrypted)
        {
            Eisight.Meter.SetMeterWithSecurityRequest inValue = new Eisight.Meter.SetMeterWithSecurityRequest();
            inValue.SecurityContext = SecurityContext;
            inValue.meterInfo = meterInfo;
            inValue.encrypted = encrypted;
            return ((Eisight.Meter.MeterSoap)(this)).SetMeterWithSecurityAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<Eisight.Meter.ResultInfo> DeleteMeterAsync(int meterID)
        {
            return base.Channel.DeleteMeterAsync(meterID);
        }
        
        public System.Threading.Tasks.Task<string> GetMeterUnitValueAsync(int meterID)
        {
            return base.Channel.GetMeterUnitValueAsync(meterID);
        }
        
        public System.Threading.Tasks.Task<string> GetSiteCodeForMeterAsync(int meterID)
        {
            return base.Channel.GetSiteCodeForMeterAsync(meterID);
        }
        
        public System.Threading.Tasks.Task<string> GetSiteMeterCodeForMeterAsync(int meterID)
        {
            return base.Channel.GetSiteMeterCodeForMeterAsync(meterID);
        }
        
        public System.Threading.Tasks.Task<Eisight.Meter.ArrayOfXElement> GetMeterTypesAsync()
        {
            return base.Channel.GetMeterTypesAsync();
        }
        
        public System.Threading.Tasks.Task<Eisight.Meter.ArrayOfXElement> GetMeterModelsAsync()
        {
            return base.Channel.GetMeterModelsAsync();
        }
        
        public System.Threading.Tasks.Task<Eisight.Meter.MeterModel> GetMeterModelAsync(int meterModelId)
        {
            return base.Channel.GetMeterModelAsync(meterModelId);
        }
        
        public System.Threading.Tasks.Task<Eisight.Meter.ArrayOfXElement> GetReadFrequenciesAsync()
        {
            return base.Channel.GetReadFrequenciesAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MeterSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.MeterSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MeterSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://esight.esightmonitoring.nl/eteck/ws/Meter.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.MeterSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://esight.esightmonitoring.nl/eteck/ws/Meter.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            MeterSoap,
            
            MeterSoap12,
        }
    }
    
    [System.Xml.Serialization.XmlSchemaProviderAttribute(null, IsAny=true)]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil-lib", "2.0.0.0")]
    public partial class ArrayOfXElement : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Collections.Generic.List<System.Xml.Linq.XElement> nodesList = new System.Collections.Generic.List<System.Xml.Linq.XElement>();
        
        public ArrayOfXElement()
        {
        }
        
        public virtual System.Collections.Generic.List<System.Xml.Linq.XElement> Nodes
        {
            get
            {
                return this.nodesList;
            }
        }
        
        public virtual System.Xml.Schema.XmlSchema GetSchema()
        {
            throw new System.NotImplementedException();
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Collections.Generic.IEnumerator<System.Xml.Linq.XElement> e = nodesList.GetEnumerator();
            for (
            ; e.MoveNext(); 
            )
            {
                ((System.Xml.Serialization.IXmlSerializable)(e.Current)).WriteXml(writer);
            }
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader)
        {
            for (
            ; (reader.NodeType != System.Xml.XmlNodeType.EndElement); 
            )
            {
                if ((reader.NodeType == System.Xml.XmlNodeType.Element))
                {
                    System.Xml.Linq.XElement elem = new System.Xml.Linq.XElement("default");
                    ((System.Xml.Serialization.IXmlSerializable)(elem)).ReadXml(reader);
                    Nodes.Add(elem);
                }
                else
                {
                    reader.Skip();
                }
            }
        }
    }
}
