//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.7.3081.0.
// 
namespace PmsEteck.Data.Models.Ketenstandaard.Invoice
{


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Invoice", Namespace="", IsNullable=false)]
    public partial class InvoiceType {
        
        private InvoiceTypeInvoiceType invoiceType1Field;
        
        private string invoiceNumberField;
        
        private System.DateTime invoiceDateField;
        
        private System.DateTime deliveryDateField;
        
        private bool deliveryDateFieldSpecified;
        
        private System.DateTime expirationDateField;
        
        private bool expirationDateFieldSpecified;
        
        private string currencyField;
        
        private InvoiceTypePaymentMethodCode paymentMethodCodeField;
        
        private bool paymentMethodCodeFieldSpecified;
        
        private AttachmentType[] attachmentField;
        
        private InvoiceTypeChainLiabilityIndicator chainLiabilityIndicatorField;
        
        private bool chainLiabilityIndicatorFieldSpecified;
        
        private string[] freeTextField;
        
        private InvoiceTypeReverseChargeIndicator reverseChargeIndicatorField;
        
        private bool reverseChargeIndicatorFieldSpecified;
        
        private string endCustomerOrderNumberField;
        
        private string despatchAdviceNumberField;
        
        private string buyersOrderNumberField;
        
        private string orderResponseNumberField;
        
        private string invoiceNumberToBeCorrectedField;
        
        private string supliersOriginalInvoiceNumberField;
        
        private string projectNumberField;
        
        private string contractNumberField;
        
        private PartyWithVATAndCertificateType buyerField;
        
        private PartyWithVATContactKvKAccountCertificateType supplierField;
        
        private PartyType invoiceeField;
        
        private PartyType invoicerField;
        
        private PartyType shipFromField;
        
        private PartyOptionalGLNType deliveryPartyField;
        
        private PartyOptionalGLNType ultimateConsigneeField;
        
        private PartyWithVATType taxRepresentativeField;
        
        private PaymentDiscountType[] paymentDiscountField;
        
        private CreditRestrictionType[] creditRestrictionField;
        
        private InvooiceChargeType[] invoiceChargeField;
        
        private InvoiceAllowanceType[] invoiceAllowanceField;
        
        private InvoiceLineType[] invoiceLineField;
        
        private PaymentOnBlockedAccountType paymentOnBlockedAccountField;
        
        private InvoiceTotalsType invoiceTotalsField;
        
        private VATSubTotalType[] vATSubTotalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InvoiceType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InvoiceTypeInvoiceType InvoiceType1 {
            get {
                return this.invoiceType1Field;
            }
            set {
                this.invoiceType1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InvoiceNumber {
            get {
                return this.invoiceNumberField;
            }
            set {
                this.invoiceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime InvoiceDate {
            get {
                return this.invoiceDateField;
            }
            set {
                this.invoiceDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime DeliveryDate {
            get {
                return this.deliveryDateField;
            }
            set {
                this.deliveryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeliveryDateSpecified {
            get {
                return this.deliveryDateFieldSpecified;
            }
            set {
                this.deliveryDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime ExpirationDate {
            get {
                return this.expirationDateField;
            }
            set {
                this.expirationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpirationDateSpecified {
            get {
                return this.expirationDateFieldSpecified;
            }
            set {
                this.expirationDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InvoiceTypePaymentMethodCode PaymentMethodCode {
            get {
                return this.paymentMethodCodeField;
            }
            set {
                this.paymentMethodCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PaymentMethodCodeSpecified {
            get {
                return this.paymentMethodCodeFieldSpecified;
            }
            set {
                this.paymentMethodCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Attachment", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AttachmentType[] Attachment {
            get {
                return this.attachmentField;
            }
            set {
                this.attachmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InvoiceTypeChainLiabilityIndicator ChainLiabilityIndicator {
            get {
                return this.chainLiabilityIndicatorField;
            }
            set {
                this.chainLiabilityIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ChainLiabilityIndicatorSpecified {
            get {
                return this.chainLiabilityIndicatorFieldSpecified;
            }
            set {
                this.chainLiabilityIndicatorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FreeText", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] FreeText {
            get {
                return this.freeTextField;
            }
            set {
                this.freeTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InvoiceTypeReverseChargeIndicator ReverseChargeIndicator {
            get {
                return this.reverseChargeIndicatorField;
            }
            set {
                this.reverseChargeIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReverseChargeIndicatorSpecified {
            get {
                return this.reverseChargeIndicatorFieldSpecified;
            }
            set {
                this.reverseChargeIndicatorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EndCustomerOrderNumber {
            get {
                return this.endCustomerOrderNumberField;
            }
            set {
                this.endCustomerOrderNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DespatchAdviceNumber {
            get {
                return this.despatchAdviceNumberField;
            }
            set {
                this.despatchAdviceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BuyersOrderNumber {
            get {
                return this.buyersOrderNumberField;
            }
            set {
                this.buyersOrderNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OrderResponseNumber {
            get {
                return this.orderResponseNumberField;
            }
            set {
                this.orderResponseNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InvoiceNumberToBeCorrected {
            get {
                return this.invoiceNumberToBeCorrectedField;
            }
            set {
                this.invoiceNumberToBeCorrectedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SupliersOriginalInvoiceNumber {
            get {
                return this.supliersOriginalInvoiceNumberField;
            }
            set {
                this.supliersOriginalInvoiceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ProjectNumber {
            get {
                return this.projectNumberField;
            }
            set {
                this.projectNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ContractNumber {
            get {
                return this.contractNumberField;
            }
            set {
                this.contractNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PartyWithVATAndCertificateType Buyer {
            get {
                return this.buyerField;
            }
            set {
                this.buyerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PartyWithVATContactKvKAccountCertificateType Supplier {
            get {
                return this.supplierField;
            }
            set {
                this.supplierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PartyType Invoicee {
            get {
                return this.invoiceeField;
            }
            set {
                this.invoiceeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PartyType Invoicer {
            get {
                return this.invoicerField;
            }
            set {
                this.invoicerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PartyType ShipFrom {
            get {
                return this.shipFromField;
            }
            set {
                this.shipFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PartyOptionalGLNType DeliveryParty {
            get {
                return this.deliveryPartyField;
            }
            set {
                this.deliveryPartyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PartyOptionalGLNType UltimateConsignee {
            get {
                return this.ultimateConsigneeField;
            }
            set {
                this.ultimateConsigneeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PartyWithVATType TaxRepresentative {
            get {
                return this.taxRepresentativeField;
            }
            set {
                this.taxRepresentativeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PaymentDiscount", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PaymentDiscountType[] PaymentDiscount {
            get {
                return this.paymentDiscountField;
            }
            set {
                this.paymentDiscountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CreditRestriction", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CreditRestrictionType[] CreditRestriction {
            get {
                return this.creditRestrictionField;
            }
            set {
                this.creditRestrictionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InvoiceCharge", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InvooiceChargeType[] InvoiceCharge {
            get {
                return this.invoiceChargeField;
            }
            set {
                this.invoiceChargeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InvoiceAllowance", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InvoiceAllowanceType[] InvoiceAllowance {
            get {
                return this.invoiceAllowanceField;
            }
            set {
                this.invoiceAllowanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InvoiceLine", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InvoiceLineType[] InvoiceLine {
            get {
                return this.invoiceLineField;
            }
            set {
                this.invoiceLineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PaymentOnBlockedAccountType PaymentOnBlockedAccount {
            get {
                return this.paymentOnBlockedAccountField;
            }
            set {
                this.paymentOnBlockedAccountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InvoiceTotalsType InvoiceTotals {
            get {
                return this.invoiceTotalsField;
            }
            set {
                this.invoiceTotalsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VATSubTotal", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VATSubTotalType[] VATSubTotal {
            get {
                return this.vATSubTotalField;
            }
            set {
                this.vATSubTotalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum InvoiceTypeInvoiceType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("380")]
        Item380,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("384")]
        Item384,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum InvoiceTypePaymentMethodCode {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10")]
        Item10,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("42")]
        Item42,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("15E")]
        Item15E,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AttachmentType {
        
        private string uRLField;
        
        private byte[] attachedDataField;
        
        private AttachmentTypeDocumentType documentTypeField;
        
        private AttachmentTypeFileType fileTypeField;
        
        private string fileNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] AttachedData {
            get {
                return this.attachedDataField;
            }
            set {
                this.attachedDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AttachmentTypeDocumentType DocumentType {
            get {
                return this.documentTypeField;
            }
            set {
                this.documentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AttachmentTypeFileType FileType {
            get {
                return this.fileTypeField;
            }
            set {
                this.fileTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum AttachmentTypeDocumentType {
        
        /// <remarks/>
        DOC,
        
        /// <remarks/>
        FAC,
        
        /// <remarks/>
        OTH,
        
        /// <remarks/>
        PIC,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum AttachmentTypeFileType {
        
        /// <remarks/>
        DOC,
        
        /// <remarks/>
        GIF,
        
        /// <remarks/>
        JPG,
        
        /// <remarks/>
        PDF,
        
        /// <remarks/>
        PNG,
        
        /// <remarks/>
        XLS,
        
        /// <remarks/>
        XML,
        
        /// <remarks/>
        ZIP,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VATInformationAndBaseAmountType {
        
        private VATInformationAndBaseAmountTypeVATRate vATRateField;
        
        private decimal vATpercentageField;
        
        private bool vATpercentageFieldSpecified;
        
        private float vATBaseAmountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VATInformationAndBaseAmountTypeVATRate VATRate {
            get {
                return this.vATRateField;
            }
            set {
                this.vATRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal VATpercentage {
            get {
                return this.vATpercentageField;
            }
            set {
                this.vATpercentageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VATpercentageSpecified {
            get {
                return this.vATpercentageFieldSpecified;
            }
            set {
                this.vATpercentageFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float VATBaseAmount {
            get {
                return this.vATBaseAmountField;
            }
            set {
                this.vATBaseAmountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum VATInformationAndBaseAmountTypeVATRate {
        
        /// <remarks/>
        E,
        
        /// <remarks/>
        S,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VATSubTotalType {
        
        private float vATAmountField;
        
        private VATInformationAndBaseAmountType vATInformationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float VATAmount {
            get {
                return this.vATAmountField;
            }
            set {
                this.vATAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VATInformationAndBaseAmountType VATInformation {
            get {
                return this.vATInformationField;
            }
            set {
                this.vATInformationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InvoiceTotalsType {
        
        private float totalInvoiceAmountField;
        
        private float totalNetLineAmountField;
        
        private float totalAmountSubjectToPaymentDiscountField;
        
        private bool totalAmountSubjectToPaymentDiscountFieldSpecified;
        
        private float totalAmountInvoiceChargeAllowanceField;
        
        private bool totalAmountInvoiceChargeAllowanceFieldSpecified;
        
        private float totalVATAmountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float TotalInvoiceAmount {
            get {
                return this.totalInvoiceAmountField;
            }
            set {
                this.totalInvoiceAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float TotalNetLineAmount {
            get {
                return this.totalNetLineAmountField;
            }
            set {
                this.totalNetLineAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float TotalAmountSubjectToPaymentDiscount {
            get {
                return this.totalAmountSubjectToPaymentDiscountField;
            }
            set {
                this.totalAmountSubjectToPaymentDiscountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalAmountSubjectToPaymentDiscountSpecified {
            get {
                return this.totalAmountSubjectToPaymentDiscountFieldSpecified;
            }
            set {
                this.totalAmountSubjectToPaymentDiscountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float TotalAmountInvoiceChargeAllowance {
            get {
                return this.totalAmountInvoiceChargeAllowanceField;
            }
            set {
                this.totalAmountInvoiceChargeAllowanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalAmountInvoiceChargeAllowanceSpecified {
            get {
                return this.totalAmountInvoiceChargeAllowanceFieldSpecified;
            }
            set {
                this.totalAmountInvoiceChargeAllowanceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float TotalVATAmount {
            get {
                return this.totalVATAmountField;
            }
            set {
                this.totalVATAmountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PaymentOnBlockedAccountType {
        
        private float amountField;
        
        private bool amountFieldSpecified;
        
        private string accountNumberField;
        
        private string iBANField;
        
        private string bICField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AmountSpecified {
            get {
                return this.amountFieldSpecified;
            }
            set {
                this.amountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AccountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IBAN {
            get {
                return this.iBANField;
            }
            set {
                this.iBANField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BIC {
            get {
                return this.bICField;
            }
            set {
                this.bICField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChargeType {
        
        private ChargeTypeChargeTypeCode chargeTypeCodeField;
        
        private float chargeAmountField;
        
        private string chargeDescriptionField;
        
        private VATInformationType vATInformationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ChargeTypeChargeTypeCode ChargeTypeCode {
            get {
                return this.chargeTypeCodeField;
            }
            set {
                this.chargeTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float ChargeAmount {
            get {
                return this.chargeAmountField;
            }
            set {
                this.chargeAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ChargeDescription {
            get {
                return this.chargeDescriptionField;
            }
            set {
                this.chargeDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VATInformationType VATInformation {
            get {
                return this.vATInformationField;
            }
            set {
                this.vATInformationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum ChargeTypeChargeTypeCode {
        
        /// <remarks/>
        ABL,
        
        /// <remarks/>
        ADR,
        
        /// <remarks/>
        AEO,
        
        /// <remarks/>
        AEP,
        
        /// <remarks/>
        CAI,
        
        /// <remarks/>
        RAD,
        
        /// <remarks/>
        SH,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VATInformationType {
        
        private VATInformationTypeVATRate vATRateField;
        
        private decimal vATPercentageField;
        
        private bool vATPercentageFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VATInformationTypeVATRate VATRate {
            get {
                return this.vATRateField;
            }
            set {
                this.vATRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal VATPercentage {
            get {
                return this.vATPercentageField;
            }
            set {
                this.vATPercentageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VATPercentageSpecified {
            get {
                return this.vATPercentageFieldSpecified;
            }
            set {
                this.vATPercentageFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum VATInformationTypeVATRate {
        
        /// <remarks/>
        E,
        
        /// <remarks/>
        S,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AllowanceType {
        
        private AllowanceTypeAllowanceTypeCode allowanceTypeCodeField;
        
        private float allowanceAmountField;
        
        private string allowanceDescriptionField;
        
        private decimal allowancePercentageField;
        
        private bool allowancePercentageFieldSpecified;
        
        private VATInformationType vATInformationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AllowanceTypeAllowanceTypeCode AllowanceTypeCode {
            get {
                return this.allowanceTypeCodeField;
            }
            set {
                this.allowanceTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float AllowanceAmount {
            get {
                return this.allowanceAmountField;
            }
            set {
                this.allowanceAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AllowanceDescription {
            get {
                return this.allowanceDescriptionField;
            }
            set {
                this.allowanceDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal AllowancePercentage {
            get {
                return this.allowancePercentageField;
            }
            set {
                this.allowancePercentageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AllowancePercentageSpecified {
            get {
                return this.allowancePercentageFieldSpecified;
            }
            set {
                this.allowancePercentageFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VATInformationType VATInformation {
            get {
                return this.vATInformationField;
            }
            set {
                this.vATInformationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum AllowanceTypeAllowanceTypeCode {
        
        /// <remarks/>
        ADO,
        
        /// <remarks/>
        ADR,
        
        /// <remarks/>
        ADZ,
        
        /// <remarks/>
        DBD,
        
        /// <remarks/>
        PAD,
        
        /// <remarks/>
        PI,
        
        /// <remarks/>
        QD,
        
        /// <remarks/>
        TD,
        
        /// <remarks/>
        WHE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PriceBaseType {
        
        private decimal numberOfUnitsInPriceBasisField;
        
        private MeasurementUnitCodeType measureUnitPriceBasisField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal NumberOfUnitsInPriceBasis {
            get {
                return this.numberOfUnitsInPriceBasisField;
            }
            set {
                this.numberOfUnitsInPriceBasisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MeasurementUnitCodeType MeasureUnitPriceBasis {
            get {
                return this.measureUnitPriceBasisField;
            }
            set {
                this.measureUnitPriceBasisField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    public enum MeasurementUnitCodeType {
        
        /// <remarks/>
        CMT,
        
        /// <remarks/>
        DAY,
        
        /// <remarks/>
        GRM,
        
        /// <remarks/>
        HUR,
        
        /// <remarks/>
        KGM,
        
        /// <remarks/>
        LTR,
        
        /// <remarks/>
        MIN,
        
        /// <remarks/>
        MLT,
        
        /// <remarks/>
        MMT,
        
        /// <remarks/>
        MTK,
        
        /// <remarks/>
        MTQ,
        
        /// <remarks/>
        MTR,
        
        /// <remarks/>
        PCE,
        
        /// <remarks/>
        TNE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PriceInformationType {
        
        private float priceField;
        
        private PriceBaseType priceBaseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PriceBaseType PriceBase {
            get {
                return this.priceBaseField;
            }
            set {
                this.priceBaseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TradeItemCertificateType {
        
        private string certificateNameField;
        
        private CertificateClaimCodeType certificateClaimCodeField;
        
        private bool certificateClaimCodeFieldSpecified;
        
        private string certificateClaimDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CertificateName {
            get {
                return this.certificateNameField;
            }
            set {
                this.certificateNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CertificateClaimCodeType CertificateClaimCode {
            get {
                return this.certificateClaimCodeField;
            }
            set {
                this.certificateClaimCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CertificateClaimCodeSpecified {
            get {
                return this.certificateClaimCodeFieldSpecified;
            }
            set {
                this.certificateClaimCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CertificateClaimDescription {
            get {
                return this.certificateClaimDescriptionField;
            }
            set {
                this.certificateClaimDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    public enum CertificateClaimCodeType {
        
        /// <remarks/>
        F100,
        
        /// <remarks/>
        F70,
        
        /// <remarks/>
        FCW,
        
        /// <remarks/>
        FMC,
        
        /// <remarks/>
        FR70,
        
        /// <remarks/>
        FRC,
        
        /// <remarks/>
        ISPM,
        
        /// <remarks/>
        KL,
        
        /// <remarks/>
        KL1,
        
        /// <remarks/>
        KL2,
        
        /// <remarks/>
        P100,
        
        /// <remarks/>
        P70,
        
        /// <remarks/>
        RW,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PhysicalDimensionsType {
        
        private decimal widthField;
        
        private bool widthFieldSpecified;
        
        private decimal lengthField;
        
        private bool lengthFieldSpecified;
        
        private decimal heightField;
        
        private bool heightFieldSpecified;
        
        private PhysicalDimensionsTypeMeasurementUnitCode measurementUnitCodeField;
        
        private bool measurementUnitCodeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WidthSpecified {
            get {
                return this.widthFieldSpecified;
            }
            set {
                this.widthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LengthSpecified {
            get {
                return this.lengthFieldSpecified;
            }
            set {
                this.lengthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HeightSpecified {
            get {
                return this.heightFieldSpecified;
            }
            set {
                this.heightFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PhysicalDimensionsTypeMeasurementUnitCode MeasurementUnitCode {
            get {
                return this.measurementUnitCodeField;
            }
            set {
                this.measurementUnitCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MeasurementUnitCodeSpecified {
            get {
                return this.measurementUnitCodeFieldSpecified;
            }
            set {
                this.measurementUnitCodeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum PhysicalDimensionsTypeMeasurementUnitCode {
        
        /// <remarks/>
        CMT,
        
        /// <remarks/>
        MMT,
        
        /// <remarks/>
        MTR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AdditionalItemIdentificationType {
        
        private string tradeItemDescriptionField;
        
        private string furtherIdentifyingCharacteristicsField;
        
        private string colourField;
        
        private PhysicalDimensionsType physicalDimensionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TradeItemDescription {
            get {
                return this.tradeItemDescriptionField;
            }
            set {
                this.tradeItemDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FurtherIdentifyingCharacteristics {
            get {
                return this.furtherIdentifyingCharacteristicsField;
            }
            set {
                this.furtherIdentifyingCharacteristicsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Colour {
            get {
                return this.colourField;
            }
            set {
                this.colourField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PhysicalDimensionsType PhysicalDimensions {
            get {
                return this.physicalDimensionsField;
            }
            set {
                this.physicalDimensionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TradeItemIdPlusAdditionalType {
        
        private string gTINField;
        
        private string suppliersTradeItemIdentificationField;
        
        private AdditionalItemIdentificationType additionalItemIdentificationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GTIN {
            get {
                return this.gTINField;
            }
            set {
                this.gTINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SuppliersTradeItemIdentification {
            get {
                return this.suppliersTradeItemIdentificationField;
            }
            set {
                this.suppliersTradeItemIdentificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AdditionalItemIdentificationType AdditionalItemIdentification {
            get {
                return this.additionalItemIdentificationField;
            }
            set {
                this.additionalItemIdentificationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InvoiceLineType {
        
        private string lineNumberField;
        
        private decimal deliveredQuantityField;
        
        private MeasurementUnitCodeType deliveredQuantityMeasureUnitCodeField;
        
        private bool deliveredQuantityMeasureUnitCodeFieldSpecified;
        
        private decimal numberOfInvoicingUnitsField;
        
        private float netLineAmountField;
        
        private TradeItemIdPlusAdditionalType tradeItemIdentificationField;
        
        private string cBSNumberField;
        
        private string[] freeTextField;
        
        private TradeItemCertificateType[] tradeItemCertificateField;
        
        private PriceInformationType priceInformationField;
        
        private VATInformationType vATInformationField;
        
        private AllowanceType[] allowanceField;
        
        private ChargeType[] chargeField;
        
        private string orderLineIdentificationField;
        
        private string despatchAdviceLineIdentificationField;
        
        private string invoiceLineToBeCorrectedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger")]
        public string LineNumber {
            get {
                return this.lineNumberField;
            }
            set {
                this.lineNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal DeliveredQuantity {
            get {
                return this.deliveredQuantityField;
            }
            set {
                this.deliveredQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MeasurementUnitCodeType DeliveredQuantityMeasureUnitCode {
            get {
                return this.deliveredQuantityMeasureUnitCodeField;
            }
            set {
                this.deliveredQuantityMeasureUnitCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeliveredQuantityMeasureUnitCodeSpecified {
            get {
                return this.deliveredQuantityMeasureUnitCodeFieldSpecified;
            }
            set {
                this.deliveredQuantityMeasureUnitCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal NumberOfInvoicingUnits {
            get {
                return this.numberOfInvoicingUnitsField;
            }
            set {
                this.numberOfInvoicingUnitsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float NetLineAmount {
            get {
                return this.netLineAmountField;
            }
            set {
                this.netLineAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TradeItemIdPlusAdditionalType TradeItemIdentification {
            get {
                return this.tradeItemIdentificationField;
            }
            set {
                this.tradeItemIdentificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CBSNumber {
            get {
                return this.cBSNumberField;
            }
            set {
                this.cBSNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FreeText", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] FreeText {
            get {
                return this.freeTextField;
            }
            set {
                this.freeTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TradeItemCertificate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TradeItemCertificateType[] TradeItemCertificate {
            get {
                return this.tradeItemCertificateField;
            }
            set {
                this.tradeItemCertificateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PriceInformationType PriceInformation {
            get {
                return this.priceInformationField;
            }
            set {
                this.priceInformationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VATInformationType VATInformation {
            get {
                return this.vATInformationField;
            }
            set {
                this.vATInformationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Allowance", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AllowanceType[] Allowance {
            get {
                return this.allowanceField;
            }
            set {
                this.allowanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Charge", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ChargeType[] Charge {
            get {
                return this.chargeField;
            }
            set {
                this.chargeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger")]
        public string OrderLineIdentification {
            get {
                return this.orderLineIdentificationField;
            }
            set {
                this.orderLineIdentificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger")]
        public string DespatchAdviceLineIdentification {
            get {
                return this.despatchAdviceLineIdentificationField;
            }
            set {
                this.despatchAdviceLineIdentificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger")]
        public string InvoiceLineToBeCorrected {
            get {
                return this.invoiceLineToBeCorrectedField;
            }
            set {
                this.invoiceLineToBeCorrectedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InvoiceAllowanceType {
        
        private InvoiceAllowanceTypeAllowanceTypeCode allowanceTypeCodeField;
        
        private float allowanceAmountField;
        
        private decimal allowancePercentageField;
        
        private bool allowancePercentageFieldSpecified;
        
        private string allowanceDescriptionField;
        
        private VATInformationType vATInformationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InvoiceAllowanceTypeAllowanceTypeCode AllowanceTypeCode {
            get {
                return this.allowanceTypeCodeField;
            }
            set {
                this.allowanceTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float AllowanceAmount {
            get {
                return this.allowanceAmountField;
            }
            set {
                this.allowanceAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal AllowancePercentage {
            get {
                return this.allowancePercentageField;
            }
            set {
                this.allowancePercentageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AllowancePercentageSpecified {
            get {
                return this.allowancePercentageFieldSpecified;
            }
            set {
                this.allowancePercentageFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AllowanceDescription {
            get {
                return this.allowanceDescriptionField;
            }
            set {
                this.allowanceDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VATInformationType VATInformation {
            get {
                return this.vATInformationField;
            }
            set {
                this.vATInformationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum InvoiceAllowanceTypeAllowanceTypeCode {
        
        /// <remarks/>
        ADO,
        
        /// <remarks/>
        ADR,
        
        /// <remarks/>
        CAC,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InvooiceChargeType {
        
        private InvooiceChargeTypeChargeTypeCode chargeTypeCodeField;
        
        private float chargeAmountField;
        
        private string chargeDescriptionField;
        
        private VATInformationType vATInformationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InvooiceChargeTypeChargeTypeCode ChargeTypeCode {
            get {
                return this.chargeTypeCodeField;
            }
            set {
                this.chargeTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float ChargeAmount {
            get {
                return this.chargeAmountField;
            }
            set {
                this.chargeAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ChargeDescription {
            get {
                return this.chargeDescriptionField;
            }
            set {
                this.chargeDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VATInformationType VATInformation {
            get {
                return this.vATInformationField;
            }
            set {
                this.vATInformationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum InvooiceChargeTypeChargeTypeCode {
        
        /// <remarks/>
        AAT,
        
        /// <remarks/>
        ADR,
        
        /// <remarks/>
        ADZ,
        
        /// <remarks/>
        AEM,
        
        /// <remarks/>
        AEQ,
        
        /// <remarks/>
        FC,
        
        /// <remarks/>
        MAC,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreditRestrictionType {
        
        private decimal percentageCreditRestrictionSurchargeField;
        
        private string numberOfDaysAfterDateOfInvoiceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PercentageCreditRestrictionSurcharge {
            get {
                return this.percentageCreditRestrictionSurchargeField;
            }
            set {
                this.percentageCreditRestrictionSurchargeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger")]
        public string NumberOfDaysAfterDateOfInvoice {
            get {
                return this.numberOfDaysAfterDateOfInvoiceField;
            }
            set {
                this.numberOfDaysAfterDateOfInvoiceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PaymentDiscountType {
        
        private decimal discountPercentageField;
        
        private string numberOfDaysAfterDateOfInvoiceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal DiscountPercentage {
            get {
                return this.discountPercentageField;
            }
            set {
                this.discountPercentageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger")]
        public string NumberOfDaysAfterDateOfInvoice {
            get {
                return this.numberOfDaysAfterDateOfInvoiceField;
            }
            set {
                this.numberOfDaysAfterDateOfInvoiceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PartyWithVATType {
        
        private string gLNField;
        
        private string nameField;
        
        private string name2Field;
        
        private string streetAndNumberField;
        
        private string cityField;
        
        private string postalCodeField;
        
        private string countryField;
        
        private string vATRegistrationNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GLN {
            get {
                return this.gLNField;
            }
            set {
                this.gLNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name2 {
            get {
                return this.name2Field;
            }
            set {
                this.name2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StreetAndNumber {
            get {
                return this.streetAndNumberField;
            }
            set {
                this.streetAndNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VATRegistrationNumber {
            get {
                return this.vATRegistrationNumberField;
            }
            set {
                this.vATRegistrationNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PartyOptionalGLNType {
        
        private string gLNField;
        
        private string nameField;
        
        private string name2Field;
        
        private string streetAndNumberField;
        
        private string cityField;
        
        private string postalCodeField;
        
        private string countryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GLN {
            get {
                return this.gLNField;
            }
            set {
                this.gLNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name2 {
            get {
                return this.name2Field;
            }
            set {
                this.name2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StreetAndNumber {
            get {
                return this.streetAndNumberField;
            }
            set {
                this.streetAndNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PartyType {
        
        private string gLNField;
        
        private string nameField;
        
        private string name2Field;
        
        private string streetAndNumberField;
        
        private string cityField;
        
        private string postalCodeField;
        
        private string countryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GLN {
            get {
                return this.gLNField;
            }
            set {
                this.gLNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name2 {
            get {
                return this.name2Field;
            }
            set {
                this.name2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StreetAndNumber {
            get {
                return this.streetAndNumberField;
            }
            set {
                this.streetAndNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AccountInformationType {
        
        private string iBANField;
        
        private string bICField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IBAN {
            get {
                return this.iBANField;
            }
            set {
                this.iBANField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BIC {
            get {
                return this.bICField;
            }
            set {
                this.bICField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ContactInformationType {
        
        private string contactPersonNameField;
        
        private string phoneNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ContactPersonName {
            get {
                return this.contactPersonNameField;
            }
            set {
                this.contactPersonNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PartyWithVATContactKvKAccountCertificateType {
        
        private string gLNField;
        
        private string nameField;
        
        private string name2Field;
        
        private string streetAndNumberField;
        
        private string cityField;
        
        private string postalCodeField;
        
        private string countryField;
        
        private string vATRegistrationNumberField;
        
        private string chamberOfCommerceNumberField;
        
        private ContactInformationType[] contactInformationField;
        
        private AccountInformationType[] accountInformationField;
        
        private CertificateType[] certificateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GLN {
            get {
                return this.gLNField;
            }
            set {
                this.gLNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name2 {
            get {
                return this.name2Field;
            }
            set {
                this.name2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StreetAndNumber {
            get {
                return this.streetAndNumberField;
            }
            set {
                this.streetAndNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VATRegistrationNumber {
            get {
                return this.vATRegistrationNumberField;
            }
            set {
                this.vATRegistrationNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ChamberOfCommerceNumber {
            get {
                return this.chamberOfCommerceNumberField;
            }
            set {
                this.chamberOfCommerceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ContactInformation", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ContactInformationType[] ContactInformation {
            get {
                return this.contactInformationField;
            }
            set {
                this.contactInformationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AccountInformation", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AccountInformationType[] AccountInformation {
            get {
                return this.accountInformationField;
            }
            set {
                this.accountInformationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Certificate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CertificateType[] Certificate {
            get {
                return this.certificateField;
            }
            set {
                this.certificateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CertificateType {
        
        private string certificateNameField;
        
        private string certificateNumberField;
        
        private string certificateIssuerField;
        
        private string certificateSubNumberField;
        
        private string certificateTextField;
        
        private System.DateTime certificateDateField;
        
        private bool certificateDateFieldSpecified;
        
        private System.DateTime certificateExpirationDateField;
        
        private bool certificateExpirationDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CertificateName {
            get {
                return this.certificateNameField;
            }
            set {
                this.certificateNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CertificateNumber {
            get {
                return this.certificateNumberField;
            }
            set {
                this.certificateNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CertificateIssuer {
            get {
                return this.certificateIssuerField;
            }
            set {
                this.certificateIssuerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CertificateSubNumber {
            get {
                return this.certificateSubNumberField;
            }
            set {
                this.certificateSubNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CertificateText {
            get {
                return this.certificateTextField;
            }
            set {
                this.certificateTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime CertificateDate {
            get {
                return this.certificateDateField;
            }
            set {
                this.certificateDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CertificateDateSpecified {
            get {
                return this.certificateDateFieldSpecified;
            }
            set {
                this.certificateDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime CertificateExpirationDate {
            get {
                return this.certificateExpirationDateField;
            }
            set {
                this.certificateExpirationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CertificateExpirationDateSpecified {
            get {
                return this.certificateExpirationDateFieldSpecified;
            }
            set {
                this.certificateExpirationDateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PartyWithVATAndCertificateType {
        
        private string gLNField;
        
        private string nameField;
        
        private string name2Field;
        
        private string streetAndNumberField;
        
        private string cityField;
        
        private string postalCodeField;
        
        private string countryField;
        
        private string vATRegistrationNumberField;
        
        private CertificateType[] certificateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GLN {
            get {
                return this.gLNField;
            }
            set {
                this.gLNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name2 {
            get {
                return this.name2Field;
            }
            set {
                this.name2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StreetAndNumber {
            get {
                return this.streetAndNumberField;
            }
            set {
                this.streetAndNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VATRegistrationNumber {
            get {
                return this.vATRegistrationNumberField;
            }
            set {
                this.vATRegistrationNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Certificate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CertificateType[] Certificate {
            get {
                return this.certificateField;
            }
            set {
                this.certificateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum InvoiceTypeChainLiabilityIndicator {
        
        /// <remarks/>
        J,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum InvoiceTypeReverseChargeIndicator {
        
        /// <remarks/>
        AC,
    }
}
