//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace VolkerWesselsServices
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0-preview-30131-0887")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://www.ketenstandaard.nl/WS/MessageService/3.1", ConfigurationName="VolkerWesselsServices.MessageServiceSoap")]
    public interface MessageServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="messageservice/GetAvailableMessages", ReplyAction="https://www.ketenstandaard.nl/WS/MessageService/3.1/MessageServiceSoap/GetAvailab" +
            "leMessagesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<VolkerWesselsServices.GetAvailableMessagesResponse> GetAvailableMessagesAsync(VolkerWesselsServices.GetAvailableMessagesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="messageservice/GetMessage", ReplyAction="https://www.ketenstandaard.nl/WS/MessageService/3.1/MessageServiceSoap/GetMessage" +
            "Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<VolkerWesselsServices.GetMessageResponse> GetMessageAsync(VolkerWesselsServices.GetMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="messageservice/DeleteMessage", ReplyAction="https://www.ketenstandaard.nl/WS/MessageService/3.1/MessageServiceSoap/DeleteMess" +
            "ageResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<VolkerWesselsServices.DeleteMessageResponse> DeleteMessageAsync(VolkerWesselsServices.DeleteMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="messageservice/PostMessage", ReplyAction="https://www.ketenstandaard.nl/WS/MessageService/3.1/MessageServiceSoap/PostMessag" +
            "eResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<VolkerWesselsServices.DeleteMessageResponse> PostMessageAsync(VolkerWesselsServices.PostMessageRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0-preview-30131-0887")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ketenstandaard.nl/WS/MessageService/3.1")]
    public partial class CustomInfoType
    {
        
        private bool isTestMessageField;
        
        private string languageCodeField;
        
        private System.Nullable<bool> isContentCompressedField;
        
        private string applicationIdField;
        
        private string versionIdField;
        
        private string relationIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool IsTestMessage
        {
            get
            {
                return this.isTestMessageField;
            }
            set
            {
                this.isTestMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string LanguageCode
        {
            get
            {
                return this.languageCodeField;
            }
            set
            {
                this.languageCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<bool> IsContentCompressed
        {
            get
            {
                return this.isContentCompressedField;
            }
            set
            {
                this.isContentCompressedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string ApplicationId
        {
            get
            {
                return this.applicationIdField;
            }
            set
            {
                this.applicationIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string VersionId
        {
            get
            {
                return this.versionIdField;
            }
            set
            {
                this.versionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string RelationId
        {
            get
            {
                return this.relationIdField;
            }
            set
            {
                this.relationIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0-preview-30131-0887")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ketenstandaard.nl/WS/MessageService/3.1")]
    public partial class MessageResponseType
    {
        
        private MessageType messageField;
        
        private bool messageResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MessageType Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool MessageResult
        {
            get
            {
                return this.messageResultField;
            }
            set
            {
                this.messageResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0-preview-30131-0887")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ketenstandaard.nl/WS/MessageService/3.1")]
    public partial class MessageType
    {
        
        private MessagePropertiesType msgPropertiesField;
        
        private string msgContentField;
        
        private AttachmentType[] attachmentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public MessagePropertiesType MsgProperties
        {
            get
            {
                return this.msgPropertiesField;
            }
            set
            {
                this.msgPropertiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MsgContent
        {
            get
            {
                return this.msgContentField;
            }
            set
            {
                this.msgContentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Attachment", Order=2)]
        public AttachmentType[] Attachment
        {
            get
            {
                return this.attachmentField;
            }
            set
            {
                this.attachmentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0-preview-30131-0887")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ketenstandaard.nl/WS/MessageService/3.1")]
    public partial class MessagePropertiesType
    {
        
        private string msgIdField;
        
        private System.DateTime msgDateTimeField;
        
        private string msgFormatField;
        
        private string msgVersionField;
        
        private string msgTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string MsgId
        {
            get
            {
                return this.msgIdField;
            }
            set
            {
                this.msgIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime MsgDateTime
        {
            get
            {
                return this.msgDateTimeField;
            }
            set
            {
                this.msgDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string MsgFormat
        {
            get
            {
                return this.msgFormatField;
            }
            set
            {
                this.msgFormatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string MsgVersion
        {
            get
            {
                return this.msgVersionField;
            }
            set
            {
                this.msgVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string MsgType
        {
            get
            {
                return this.msgTypeField;
            }
            set
            {
                this.msgTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0-preview-30131-0887")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ketenstandaard.nl/WS/MessageService/3.1")]
    public partial class AttachmentType
    {
        
        private string uRLField;
        
        private string documentTypeField;
        
        private string fileTypeField;
        
        private string fileNameField;
        
        private byte[] attachedDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string URL
        {
            get
            {
                return this.uRLField;
            }
            set
            {
                this.uRLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DocumentType
        {
            get
            {
                return this.documentTypeField;
            }
            set
            {
                this.documentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FileType
        {
            get
            {
                return this.fileTypeField;
            }
            set
            {
                this.fileTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string FileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true, Order=4)]
        public byte[] AttachedData
        {
            get
            {
                return this.attachedDataField;
            }
            set
            {
                this.attachedDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0-preview-30131-0887")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ketenstandaard.nl/WS/MessageService/3.1")]
    public partial class MessageRequestResponseType
    {
        
        private MessageType messageRequestResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MessageType MessageRequestResult
        {
            get
            {
                return this.messageRequestResultField;
            }
            set
            {
                this.messageRequestResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0-preview-30131-0887")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ketenstandaard.nl/WS/MessageService/3.1")]
    public partial class MessageRequestType
    {
        
        private string msgIdField;
        
        private string msgFormatField;
        
        private string msgVersionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string MsgId
        {
            get
            {
                return this.msgIdField;
            }
            set
            {
                this.msgIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string MsgFormat
        {
            get
            {
                return this.msgFormatField;
            }
            set
            {
                this.msgFormatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string MsgVersion
        {
            get
            {
                return this.msgVersionField;
            }
            set
            {
                this.msgVersionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0-preview-30131-0887")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ketenstandaard.nl/WS/MessageService/3.1")]
    public partial class AvailableMessagesRequestType
    {
        
        private string msgTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string MsgType
        {
            get
            {
                return this.msgTypeField;
            }
            set
            {
                this.msgTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0-preview-30131-0887")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAvailableMessagesRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://www.ketenstandaard.nl/WS/MessageService/3.1")]
        public VolkerWesselsServices.CustomInfoType CustomInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.ketenstandaard.nl/WS/MessageService/3.1", Order=0)]
        public VolkerWesselsServices.AvailableMessagesRequestType AvailableMessagesRequest;
        
        public GetAvailableMessagesRequest()
        {
        }
        
        public GetAvailableMessagesRequest(VolkerWesselsServices.CustomInfoType CustomInfo, VolkerWesselsServices.AvailableMessagesRequestType AvailableMessagesRequest)
        {
            this.CustomInfo = CustomInfo;
            this.AvailableMessagesRequest = AvailableMessagesRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0-preview-30131-0887")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAvailableMessagesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.ketenstandaard.nl/WS/MessageService/3.1", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("MessageList")]
        public VolkerWesselsServices.MessagePropertiesType[] AvailableMessagesResponse;
        
        public GetAvailableMessagesResponse()
        {
        }
        
        public GetAvailableMessagesResponse(VolkerWesselsServices.MessagePropertiesType[] AvailableMessagesResponse)
        {
            this.AvailableMessagesResponse = AvailableMessagesResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0-preview-30131-0887")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessageRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://www.ketenstandaard.nl/WS/MessageService/3.1")]
        public VolkerWesselsServices.CustomInfoType CustomInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.ketenstandaard.nl/WS/MessageService/3.1", Order=0)]
        public VolkerWesselsServices.MessageRequestType MessageRequest;
        
        public GetMessageRequest()
        {
        }
        
        public GetMessageRequest(VolkerWesselsServices.CustomInfoType CustomInfo, VolkerWesselsServices.MessageRequestType MessageRequest)
        {
            this.CustomInfo = CustomInfo;
            this.MessageRequest = MessageRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0-preview-30131-0887")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessageResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.ketenstandaard.nl/WS/MessageService/3.1", Order=0)]
        public VolkerWesselsServices.MessageRequestResponseType MessageRequestResponse;
        
        public GetMessageResponse()
        {
        }
        
        public GetMessageResponse(VolkerWesselsServices.MessageRequestResponseType MessageRequestResponse)
        {
            this.MessageRequestResponse = MessageRequestResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0-preview-30131-0887")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteMessageRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://www.ketenstandaard.nl/WS/MessageService/3.1")]
        public VolkerWesselsServices.CustomInfoType CustomInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.ketenstandaard.nl/WS/MessageService/3.1", Order=0)]
        public VolkerWesselsServices.MessageRequestType MessageRequest;
        
        public DeleteMessageRequest()
        {
        }
        
        public DeleteMessageRequest(VolkerWesselsServices.CustomInfoType CustomInfo, VolkerWesselsServices.MessageRequestType MessageRequest)
        {
            this.CustomInfo = CustomInfo;
            this.MessageRequest = MessageRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0-preview-30131-0887")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteMessageResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.ketenstandaard.nl/WS/MessageService/3.1", Order=0)]
        public VolkerWesselsServices.MessageResponseType MessageResponse;
        
        public DeleteMessageResponse()
        {
        }
        
        public DeleteMessageResponse(VolkerWesselsServices.MessageResponseType MessageResponse)
        {
            this.MessageResponse = MessageResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0-preview-30131-0887")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostMessageRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://www.ketenstandaard.nl/WS/MessageService/3.1")]
        public VolkerWesselsServices.CustomInfoType CustomInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.ketenstandaard.nl/WS/MessageService/3.1", Order=0)]
        public VolkerWesselsServices.MessageType Message;
        
        public PostMessageRequest()
        {
        }
        
        public PostMessageRequest(VolkerWesselsServices.CustomInfoType CustomInfo, VolkerWesselsServices.MessageType Message)
        {
            this.CustomInfo = CustomInfo;
            this.Message = Message;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0-preview-30131-0887")]
    public interface MessageServiceSoapChannel : VolkerWesselsServices.MessageServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0-preview-30131-0887")]
    public partial class MessageServiceSoapClient : System.ServiceModel.ClientBase<VolkerWesselsServices.MessageServiceSoap>, VolkerWesselsServices.MessageServiceSoap
    {
        
        public MessageServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VolkerWesselsServices.GetAvailableMessagesResponse> VolkerWesselsServices.MessageServiceSoap.GetAvailableMessagesAsync(VolkerWesselsServices.GetAvailableMessagesRequest request)
        {
            return base.Channel.GetAvailableMessagesAsync(request);
        }
        
        public System.Threading.Tasks.Task<VolkerWesselsServices.GetAvailableMessagesResponse> GetAvailableMessagesAsync(VolkerWesselsServices.CustomInfoType CustomInfo, VolkerWesselsServices.AvailableMessagesRequestType AvailableMessagesRequest)
        {
            VolkerWesselsServices.GetAvailableMessagesRequest inValue = new VolkerWesselsServices.GetAvailableMessagesRequest();
            inValue.CustomInfo = CustomInfo;
            inValue.AvailableMessagesRequest = AvailableMessagesRequest;
            return ((VolkerWesselsServices.MessageServiceSoap)(this)).GetAvailableMessagesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VolkerWesselsServices.GetMessageResponse> VolkerWesselsServices.MessageServiceSoap.GetMessageAsync(VolkerWesselsServices.GetMessageRequest request)
        {
            return base.Channel.GetMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<VolkerWesselsServices.GetMessageResponse> GetMessageAsync(VolkerWesselsServices.CustomInfoType CustomInfo, VolkerWesselsServices.MessageRequestType MessageRequest)
        {
            VolkerWesselsServices.GetMessageRequest inValue = new VolkerWesselsServices.GetMessageRequest();
            inValue.CustomInfo = CustomInfo;
            inValue.MessageRequest = MessageRequest;
            return ((VolkerWesselsServices.MessageServiceSoap)(this)).GetMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VolkerWesselsServices.DeleteMessageResponse> VolkerWesselsServices.MessageServiceSoap.DeleteMessageAsync(VolkerWesselsServices.DeleteMessageRequest request)
        {
            return base.Channel.DeleteMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<VolkerWesselsServices.DeleteMessageResponse> DeleteMessageAsync(VolkerWesselsServices.CustomInfoType CustomInfo, VolkerWesselsServices.MessageRequestType MessageRequest)
        {
            VolkerWesselsServices.DeleteMessageRequest inValue = new VolkerWesselsServices.DeleteMessageRequest();
            inValue.CustomInfo = CustomInfo;
            inValue.MessageRequest = MessageRequest;
            return ((VolkerWesselsServices.MessageServiceSoap)(this)).DeleteMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VolkerWesselsServices.DeleteMessageResponse> VolkerWesselsServices.MessageServiceSoap.PostMessageAsync(VolkerWesselsServices.PostMessageRequest request)
        {
            return base.Channel.PostMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<VolkerWesselsServices.DeleteMessageResponse> PostMessageAsync(VolkerWesselsServices.CustomInfoType CustomInfo, VolkerWesselsServices.MessageType Message)
        {
            VolkerWesselsServices.PostMessageRequest inValue = new VolkerWesselsServices.PostMessageRequest();
            inValue.CustomInfo = CustomInfo;
            inValue.Message = Message;
            return ((VolkerWesselsServices.MessageServiceSoap)(this)).PostMessageAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }

        internal void PostMessageAsync(MessageType a)
        {
            throw new NotImplementedException();
        }
    }
}
