//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eisight.Site
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0-preview-30131-0887")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.esightenergy.com/esight/WS/", ConfigurationName="Eisight.Site.SiteSoap")]
    public interface SiteSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.esightenergy.com/esight/WS/GetSiteIDFromCompanyIDAndSiteName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> GetSiteIDFromCompanyIDAndSiteNameAsync(int companyID, string siteName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.esightenergy.com/esight/WS/GetSiteIDFromCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> GetSiteIDFromCodeAsync(string siteCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.esightenergy.com/esight/WS/GetSites", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Eisight.Site.ArrayOfXElement> GetSitesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.esightenergy.com/esight/WS/GetSitesForCompanyID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Eisight.Site.ArrayOfXElement> GetSitesForCompanyIDAsync(int companyID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.esightenergy.com/esight/WS/GetSite", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Eisight.Site.SiteInfo> GetSiteAsync(int siteID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.esightenergy.com/esight/WS/SetSite", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Eisight.Site.ResultInfo> SetSiteAsync(Eisight.Site.SiteInfo siteInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.esightenergy.com/esight/WS/DeleteSite", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Eisight.Site.ResultInfo> DeleteSiteAsync(int siteID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.esightenergy.com/esight/WS/GetMetersForSiteID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Eisight.Site.ArrayOfXElement> GetMetersForSiteIDAsync(int siteid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.esightenergy.com/esight/WS/GetTemplatesForSite", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Eisight.Site.ArrayOfXElement> GetTemplatesForSiteAsync(int siteid);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0-preview-30131-0887")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esightenergy.com/esight/WS/")]
    public partial class ResultInfo
    {
        
        private bool successField;
        
        private int updateIDField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Success
        {
            get
            {
                return this.successField;
            }
            set
            {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int UpdateID
        {
            get
            {
                return this.updateIDField;
            }
            set
            {
                this.updateIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ErrorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0-preview-30131-0887")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esightenergy.com/esight/WS/")]
    public partial class clsActivePeriodInfo
    {
        
        private int activePeriodIDField;
        
        private int siteIDField;
        
        private int meterIDField;
        
        private int fromMonthField;
        
        private int toMonthField;
        
        private int fromDayField;
        
        private int toDayField;
        
        private int fromTimeField;
        
        private int toTimeField;
        
        private int percentageActiveField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ActivePeriodID
        {
            get
            {
                return this.activePeriodIDField;
            }
            set
            {
                this.activePeriodIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int SiteID
        {
            get
            {
                return this.siteIDField;
            }
            set
            {
                this.siteIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int MeterID
        {
            get
            {
                return this.meterIDField;
            }
            set
            {
                this.meterIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int FromMonth
        {
            get
            {
                return this.fromMonthField;
            }
            set
            {
                this.fromMonthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int ToMonth
        {
            get
            {
                return this.toMonthField;
            }
            set
            {
                this.toMonthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int FromDay
        {
            get
            {
                return this.fromDayField;
            }
            set
            {
                this.fromDayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int ToDay
        {
            get
            {
                return this.toDayField;
            }
            set
            {
                this.toDayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int FromTime
        {
            get
            {
                return this.fromTimeField;
            }
            set
            {
                this.fromTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int ToTime
        {
            get
            {
                return this.toTimeField;
            }
            set
            {
                this.toTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int PercentageActive
        {
            get
            {
                return this.percentageActiveField;
            }
            set
            {
                this.percentageActiveField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0-preview-30131-0887")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esightenergy.com/esight/WS/")]
    public partial class SiteInfo
    {
        
        private int siteIDField;
        
        private int parentTypeIDField;
        
        private int parentIDField;
        
        private string nameField;
        
        private string siteCodeField;
        
        private string address1Field;
        
        private string address2Field;
        
        private string address3Field;
        
        private string cityField;
        
        private string countyField;
        
        private string postCodeField;
        
        private int countryIDField;
        
        private int timezoneIDField;
        
        private int lDZIDField;
        
        private int dDRegionIDField;
        
        private string imageFileNameField;
        
        private int buildingTypeIDField;
        
        private int benchmarkStandardIDField;
        
        private int benchmarkDataDescriptionIDField;
        
        private double treatedFloorAreaM2Field;
        
        private double volumeM3Field;
        
        private int numberOfOccupantsField;
        
        private double occupancyHoursField;
        
        private double percentOfElecConsumptionAffectedByDegreeDaysField;
        
        private double percentOfFossileConsumptionAffectedBydegreeDaysField;
        
        private int benchmarkingExposureIDField;
        
        private bool metricField;
        
        private double areaField;
        
        private int userDefinedLookupID1Field;
        
        private int userDefinedLookupID2Field;
        
        private string userDefinedTxtbox1Field;
        
        private string userDefinedTxtbox2Field;
        
        private bool eAMCTSAccreditationField;
        
        private clsActivePeriodInfo[] activePeriodsListField;
        
        private System.Nullable<int> sitePublicHolidayPercentActiveField;
        
        private int emissionsRegionIDField;
        
        private string companyRegisteredNumberField;
        
        private string contractNumberField;
        
        private System.Nullable<System.DateTime> startDateField;
        
        private System.Nullable<System.DateTime> endDateField;
        
        private string costCentreField;
        
        private int subCompanyIDField;
        
        private string linkURLField;
        
        private int treeViewIconIDField;
        
        private int eTTemp1Field;
        
        private int eTTemp2Field;
        
        private int eTTemp3Field;
        
        private int eTTemp4Field;
        
        private int eTTemp5Field;
        
        private int eTPlusField;
        
        private int eTMinusField;
        
        private int eTTempMeterIDField;
        
        private double eTTemp1ConsumpWField;
        
        private double eTTemp2ConsumpWField;
        
        private double eTTemp3ConsumpWField;
        
        private double eTTemp4ConsumpWField;
        
        private double eTTemp5ConsumpWField;
        
        private double eTTemp1ConsumpMField;
        
        private double eTTemp2ConsumpMField;
        
        private double eTTemp3ConsumpMField;
        
        private double eTTemp4ConsumpMField;
        
        private double eTTemp5ConsumpMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int SiteID
        {
            get
            {
                return this.siteIDField;
            }
            set
            {
                this.siteIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ParentTypeID
        {
            get
            {
                return this.parentTypeIDField;
            }
            set
            {
                this.parentTypeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int ParentID
        {
            get
            {
                return this.parentIDField;
            }
            set
            {
                this.parentIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SiteCode
        {
            get
            {
                return this.siteCodeField;
            }
            set
            {
                this.siteCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Address1
        {
            get
            {
                return this.address1Field;
            }
            set
            {
                this.address1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Address2
        {
            get
            {
                return this.address2Field;
            }
            set
            {
                this.address2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Address3
        {
            get
            {
                return this.address3Field;
            }
            set
            {
                this.address3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string County
        {
            get
            {
                return this.countyField;
            }
            set
            {
                this.countyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string PostCode
        {
            get
            {
                return this.postCodeField;
            }
            set
            {
                this.postCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int CountryID
        {
            get
            {
                return this.countryIDField;
            }
            set
            {
                this.countryIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int TimezoneID
        {
            get
            {
                return this.timezoneIDField;
            }
            set
            {
                this.timezoneIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int LDZID
        {
            get
            {
                return this.lDZIDField;
            }
            set
            {
                this.lDZIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int DDRegionID
        {
            get
            {
                return this.dDRegionIDField;
            }
            set
            {
                this.dDRegionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string ImageFileName
        {
            get
            {
                return this.imageFileNameField;
            }
            set
            {
                this.imageFileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public int BuildingTypeID
        {
            get
            {
                return this.buildingTypeIDField;
            }
            set
            {
                this.buildingTypeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public int BenchmarkStandardID
        {
            get
            {
                return this.benchmarkStandardIDField;
            }
            set
            {
                this.benchmarkStandardIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public int BenchmarkDataDescriptionID
        {
            get
            {
                return this.benchmarkDataDescriptionIDField;
            }
            set
            {
                this.benchmarkDataDescriptionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public double TreatedFloorAreaM2
        {
            get
            {
                return this.treatedFloorAreaM2Field;
            }
            set
            {
                this.treatedFloorAreaM2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public double VolumeM3
        {
            get
            {
                return this.volumeM3Field;
            }
            set
            {
                this.volumeM3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public int NumberOfOccupants
        {
            get
            {
                return this.numberOfOccupantsField;
            }
            set
            {
                this.numberOfOccupantsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public double OccupancyHours
        {
            get
            {
                return this.occupancyHoursField;
            }
            set
            {
                this.occupancyHoursField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public double PercentOfElecConsumptionAffectedByDegreeDays
        {
            get
            {
                return this.percentOfElecConsumptionAffectedByDegreeDaysField;
            }
            set
            {
                this.percentOfElecConsumptionAffectedByDegreeDaysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public double PercentOfFossileConsumptionAffectedBydegreeDays
        {
            get
            {
                return this.percentOfFossileConsumptionAffectedBydegreeDaysField;
            }
            set
            {
                this.percentOfFossileConsumptionAffectedBydegreeDaysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public int BenchmarkingExposureID
        {
            get
            {
                return this.benchmarkingExposureIDField;
            }
            set
            {
                this.benchmarkingExposureIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public bool Metric
        {
            get
            {
                return this.metricField;
            }
            set
            {
                this.metricField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public double Area
        {
            get
            {
                return this.areaField;
            }
            set
            {
                this.areaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public int UserDefinedLookupID1
        {
            get
            {
                return this.userDefinedLookupID1Field;
            }
            set
            {
                this.userDefinedLookupID1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public int UserDefinedLookupID2
        {
            get
            {
                return this.userDefinedLookupID2Field;
            }
            set
            {
                this.userDefinedLookupID2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string UserDefinedTxtbox1
        {
            get
            {
                return this.userDefinedTxtbox1Field;
            }
            set
            {
                this.userDefinedTxtbox1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string UserDefinedTxtbox2
        {
            get
            {
                return this.userDefinedTxtbox2Field;
            }
            set
            {
                this.userDefinedTxtbox2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public bool EAMCTSAccreditation
        {
            get
            {
                return this.eAMCTSAccreditationField;
            }
            set
            {
                this.eAMCTSAccreditationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=33)]
        public clsActivePeriodInfo[] ActivePeriodsList
        {
            get
            {
                return this.activePeriodsListField;
            }
            set
            {
                this.activePeriodsListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=34)]
        public System.Nullable<int> SitePublicHolidayPercentActive
        {
            get
            {
                return this.sitePublicHolidayPercentActiveField;
            }
            set
            {
                this.sitePublicHolidayPercentActiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public int EmissionsRegionID
        {
            get
            {
                return this.emissionsRegionIDField;
            }
            set
            {
                this.emissionsRegionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public string CompanyRegisteredNumber
        {
            get
            {
                return this.companyRegisteredNumberField;
            }
            set
            {
                this.companyRegisteredNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public string ContractNumber
        {
            get
            {
                return this.contractNumberField;
            }
            set
            {
                this.contractNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=38)]
        public System.Nullable<System.DateTime> StartDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=39)]
        public System.Nullable<System.DateTime> EndDate
        {
            get
            {
                return this.endDateField;
            }
            set
            {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public string CostCentre
        {
            get
            {
                return this.costCentreField;
            }
            set
            {
                this.costCentreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public int SubCompanyID
        {
            get
            {
                return this.subCompanyIDField;
            }
            set
            {
                this.subCompanyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=42)]
        public string LinkURL
        {
            get
            {
                return this.linkURLField;
            }
            set
            {
                this.linkURLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=43)]
        public int TreeViewIconID
        {
            get
            {
                return this.treeViewIconIDField;
            }
            set
            {
                this.treeViewIconIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=44)]
        public int ETTemp1
        {
            get
            {
                return this.eTTemp1Field;
            }
            set
            {
                this.eTTemp1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=45)]
        public int ETTemp2
        {
            get
            {
                return this.eTTemp2Field;
            }
            set
            {
                this.eTTemp2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=46)]
        public int ETTemp3
        {
            get
            {
                return this.eTTemp3Field;
            }
            set
            {
                this.eTTemp3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=47)]
        public int ETTemp4
        {
            get
            {
                return this.eTTemp4Field;
            }
            set
            {
                this.eTTemp4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=48)]
        public int ETTemp5
        {
            get
            {
                return this.eTTemp5Field;
            }
            set
            {
                this.eTTemp5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=49)]
        public int ETPlus
        {
            get
            {
                return this.eTPlusField;
            }
            set
            {
                this.eTPlusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=50)]
        public int ETMinus
        {
            get
            {
                return this.eTMinusField;
            }
            set
            {
                this.eTMinusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=51)]
        public int ETTempMeterID
        {
            get
            {
                return this.eTTempMeterIDField;
            }
            set
            {
                this.eTTempMeterIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=52)]
        public double ETTemp1ConsumpW
        {
            get
            {
                return this.eTTemp1ConsumpWField;
            }
            set
            {
                this.eTTemp1ConsumpWField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=53)]
        public double ETTemp2ConsumpW
        {
            get
            {
                return this.eTTemp2ConsumpWField;
            }
            set
            {
                this.eTTemp2ConsumpWField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=54)]
        public double ETTemp3ConsumpW
        {
            get
            {
                return this.eTTemp3ConsumpWField;
            }
            set
            {
                this.eTTemp3ConsumpWField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=55)]
        public double ETTemp4ConsumpW
        {
            get
            {
                return this.eTTemp4ConsumpWField;
            }
            set
            {
                this.eTTemp4ConsumpWField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=56)]
        public double ETTemp5ConsumpW
        {
            get
            {
                return this.eTTemp5ConsumpWField;
            }
            set
            {
                this.eTTemp5ConsumpWField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=57)]
        public double ETTemp1ConsumpM
        {
            get
            {
                return this.eTTemp1ConsumpMField;
            }
            set
            {
                this.eTTemp1ConsumpMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=58)]
        public double ETTemp2ConsumpM
        {
            get
            {
                return this.eTTemp2ConsumpMField;
            }
            set
            {
                this.eTTemp2ConsumpMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=59)]
        public double ETTemp3ConsumpM
        {
            get
            {
                return this.eTTemp3ConsumpMField;
            }
            set
            {
                this.eTTemp3ConsumpMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=60)]
        public double ETTemp4ConsumpM
        {
            get
            {
                return this.eTTemp4ConsumpMField;
            }
            set
            {
                this.eTTemp4ConsumpMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=61)]
        public double ETTemp5ConsumpM
        {
            get
            {
                return this.eTTemp5ConsumpMField;
            }
            set
            {
                this.eTTemp5ConsumpMField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0-preview-30131-0887")]
    public interface SiteSoapChannel : Eisight.Site.SiteSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0-preview-30131-0887")]
    public partial class SiteSoapClient : System.ServiceModel.ClientBase<Eisight.Site.SiteSoap>, Eisight.Site.SiteSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SiteSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(SiteSoapClient.GetBindingForEndpoint(endpointConfiguration), SiteSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SiteSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SiteSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SiteSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SiteSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SiteSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<int> GetSiteIDFromCompanyIDAndSiteNameAsync(int companyID, string siteName)
        {
            return base.Channel.GetSiteIDFromCompanyIDAndSiteNameAsync(companyID, siteName);
        }
        
        public System.Threading.Tasks.Task<int> GetSiteIDFromCodeAsync(string siteCode)
        {
            return base.Channel.GetSiteIDFromCodeAsync(siteCode);
        }
        
        public System.Threading.Tasks.Task<Eisight.Site.ArrayOfXElement> GetSitesAsync()
        {
            return base.Channel.GetSitesAsync();
        }
        
        public System.Threading.Tasks.Task<Eisight.Site.ArrayOfXElement> GetSitesForCompanyIDAsync(int companyID)
        {
            return base.Channel.GetSitesForCompanyIDAsync(companyID);
        }
        
        public System.Threading.Tasks.Task<Eisight.Site.SiteInfo> GetSiteAsync(int siteID)
        {
            return base.Channel.GetSiteAsync(siteID);
        }
        
        public System.Threading.Tasks.Task<Eisight.Site.ResultInfo> SetSiteAsync(Eisight.Site.SiteInfo siteInfo)
        {
            return base.Channel.SetSiteAsync(siteInfo);
        }
        
        public System.Threading.Tasks.Task<Eisight.Site.ResultInfo> DeleteSiteAsync(int siteID)
        {
            return base.Channel.DeleteSiteAsync(siteID);
        }
        
        public System.Threading.Tasks.Task<Eisight.Site.ArrayOfXElement> GetMetersForSiteIDAsync(int siteid)
        {
            return base.Channel.GetMetersForSiteIDAsync(siteid);
        }
        
        public System.Threading.Tasks.Task<Eisight.Site.ArrayOfXElement> GetTemplatesForSiteAsync(int siteid)
        {
            return base.Channel.GetTemplatesForSiteAsync(siteid);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SiteSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.SiteSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SiteSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://esight.esightmonitoring.nl/eteck/ws/Site.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.SiteSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://esight.esightmonitoring.nl/eteck/ws/Site.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            SiteSoap,
            
            SiteSoap12,
        }
    }
    
    [System.Xml.Serialization.XmlSchemaProviderAttribute(null, IsAny=true)]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil-lib", "2.0.0.0")]
    public partial class ArrayOfXElement : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Collections.Generic.List<System.Xml.Linq.XElement> nodesList = new System.Collections.Generic.List<System.Xml.Linq.XElement>();
        
        public ArrayOfXElement()
        {
        }
        
        public virtual System.Collections.Generic.List<System.Xml.Linq.XElement> Nodes
        {
            get
            {
                return this.nodesList;
            }
        }
        
        public virtual System.Xml.Schema.XmlSchema GetSchema()
        {
            throw new System.NotImplementedException();
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Collections.Generic.IEnumerator<System.Xml.Linq.XElement> e = nodesList.GetEnumerator();
            for (
            ; e.MoveNext(); 
            )
            {
                ((System.Xml.Serialization.IXmlSerializable)(e.Current)).WriteXml(writer);
            }
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader)
        {
            for (
            ; (reader.NodeType != System.Xml.XmlNodeType.EndElement); 
            )
            {
                if ((reader.NodeType == System.Xml.XmlNodeType.Element))
                {
                    System.Xml.Linq.XElement elem = new System.Xml.Linq.XElement("default");
                    ((System.Xml.Serialization.IXmlSerializable)(elem)).ReadXml(reader);
                    Nodes.Add(elem);
                }
                else
                {
                    reader.Skip();
                }
            }
        }
    }
}
